version: '3'
services:
  filter_inbound_1:
    command: python3 main.py ./config/filter_inbound.json 1 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_inbound_2:
    command: python3 main.py ./config/filter_inbound.json 1 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_columns_1:
    build: .
    command: python3 main.py ./config/filter_columns.json 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_columns_2:
    build: .
    command: python3 main.py ./config/filter_columns.json 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  text_processing_1:
    build: .
    command: python3 main.py ./config/text_processing.json 2 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  text_processing_2:
    build: .
    command: python3 main.py ./config/text_processing.json 2 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_user_1:
    build: .
    command: python3 main.py ./config/filter_user.json 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_user_2:
    build: .
    command: python3 main.py ./config/filter_user.json 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_date_1:
    build: .
    command: python3 main.py ./config/filter_date.json 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  filter_date_2:
    build: .
    command: python3 main.py ./config/filter_date.json 2 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
    environment:
        - PYTHONUNBUFFERED=1
  aggregator_users_1:
    build: .
    command: python3 main.py ./config/aggregator_users.json 2 1
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
        - ./results:/TP2/results
    environment:
        - PYTHONUNBUFFERED=1
  aggregator_users_2:
    build: .
    command: python3 main.py ./config/aggregator_users.json 2 1
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
        - ./results:/TP2/results
    environment:
        - PYTHONUNBUFFERED=1
  aggregator_total_1:
    build: .
    command: python3 main.py ./config/aggregator_total.json 2 1
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
        - ./results:/TP2/results
    environment:
        - PYTHONUNBUFFERED=1
  aggregator_total_2:
    build: .
    command: python3 main.py ./config/aggregator_total.json 2 1
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
        - ./results:/TP2/results
    environment:
        - PYTHONUNBUFFERED=1
  sink_users:
    build: .
    command: python3 main.py ./config/sink_users.json 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
        - ./results:/TP2/results
    environment:
        - PYTHONUNBUFFERED=1
  sink_total:
    build: .
    command: python3 main.py ./config/sink_total.json 2
    image: 7574-tp2
    volumes:
        - ./config:/TP2/config
        - ./results:/TP2/results
    environment:
        - PYTHONUNBUFFERED=1
