version: '3'
services:
  dispatcher:
    build:
      context: ./
      dockerfile: Dockerfile.dispatcher
    environment:
        - PYTHONUNBUFFERED=1
  filter_inbound_1:
    build:
      context: ./
      dockerfile: Dockerfile.filter_inbound
    environment:
      - PYTHONUNBUFFERED=1
  filter_columns_1:
    build:
      context: ./
      dockerfile: Dockerfile.filter_columns
    environment:
      - PYTHONUNBUFFERED=1
  text_processing_1:
    build:
      context: ./
      dockerfile: Dockerfile.text_processing
    environment:
      - PYTHONUNBUFFERED=1
  aggregator_users:
    build:
      context: ./
      dockerfile: Dockerfile.aggregator_users
    environment:
      - PYTHONUNBUFFERED=1
  aggregator_total:
    build:
      context: ./
      dockerfile: Dockerfile.aggregator_total
    environment:
      - PYTHONUNBUFFERED=1
